# Generated by Django 5.2.3 on 2025-06-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Medico',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='doctor',
            new_name='medico',
        ),
    ]
